### PR TITLE
Port to GTK 4

### PR DESCRIPTION
**Pull request by vanillajonathan**
However unlikely, it just so happens that this has been ported to GTK 4 in all of its glory!

### CODE REVIEW

**Comment by vanillajonathan** [comment]
Hey @mattn !

**Comment by vanillajonathan** [comment]
Hey @mattn, merge this!

**Comment by vanillajonathan** [comment]
Hey @mattn, please merge this!

**Comment by mattn** [comment]
okax. please take me while to check.

**Comment by mattn** [comment]
Thank you

**Pull request merged**
